package com.cat.dataobject;

public class CatDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.id
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.url
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.vote
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    private Integer vote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.id
     *
     * @return the value of cat.id
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.id
     *
     * @param id the value for cat.id
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.url
     *
     * @return the value of cat.url
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.url
     *
     * @param url the value for cat.url
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.vote
     *
     * @return the value of cat.vote
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    public Integer getVote() {
        return vote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.vote
     *
     * @param vote the value for cat.vote
     *
     * @mbggenerated Tue Jan 04 14:55:04 CET 2022
     */
    public void setVote(Integer vote) {
        this.vote = vote;
    }
}